stages:
  - test
  - build

test-backend:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend/EmsApi.Tests
    - dotnet restore
    - dotnet test

test-frontend:
  stage: test
  image: node:20-alpine
  script:
    - cd frontend/emp_manage
    - npm ci
    - npm run test -- --watch=false

build-backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend/EmsApi
    - dotnet restore
    - dotnet build --configuration Release

build-frontend:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend/emp_manage
    - npm ci
    - npm run build -- --configuration production
